syntax = "proto3";
package cosmwasm.txfees.v1;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "cosmwasm/txfees/v1/params.proto";
import "cosmwasm/txfees/v1/fee_token.proto";

option go_package = "github.com/CosmWasm/wasmd/x/txfees/types";

// Query defines the gRPC querier service.
service Query {
  // Params defines a gRPC query method that returns the txfees module's
  // parameters.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/cosmwasm/txfees/v1/params";
  }

  // AllowedTokens defines a gRPC query method that returns the allowed tokens can be charge fees
  rpc AllowedTokens(QueryAllowedTokensRequest) returns (QueryAllowedTokensResponse) {
    option (google.api.http).get = "/cosmwasm/txfees/v1/allowed_tokens";
  }

  // TokensConfig defines a gRPC query method that returns the fee configuration of allowed tokens
  rpc TokensConfig(QueryTokensConfigRequest) returns (QueryTokensConfigResponse) {
    option (google.api.http).get = "/cosmwasm/txfees/v1/tokens_config";
  }

  // TokenConfig defines a gRPC query method that returns the fee configuration of allowed token
  rpc TokenConfig(QueryTokenConfigRequest) returns (QueryTokenConfigResponse) {
    option (google.api.http).get = "/cosmwasm/txfees/v1/token_config";
  }
}

// QueryParamsRequest is the request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is the response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params defines the parameters of the module.
  Params params = 1 [ (gogoproto.nullable) = false ];
}

// QueryAllowedTokensRequest is the request type for the Query/AllowedTokens RPC method.
message QueryAllowedTokensRequest {}

// QueryAllowedTokensResponse is the response type for the Query/AllowedTokens RPC method.
message QueryAllowedTokensResponse {
  // tokens defines the parameters of the module.
  repeated string tokens = 1 [ (gogoproto.nullable) = false ];
}

// QueryTokensConfigRequest is the request type for the Query/TokensConfig RPC method.
message QueryTokensConfigRequest {}

// QueryTokensConfigResponse is the response type for the Query/TokensConfig RPC method.
message QueryTokensConfigResponse {
  // configs defines the parameters of the module.
  repeated FeeTokenConfiguration configs = 1 [ (gogoproto.nullable) = false ];
}

// QueryTokenConfigRequest is the request type for the Query/TokenConfig RPC method.
message QueryTokenConfigRequest {
  // denom defines the parameters of the module.
  string denom = 1;
}

// QueryTokenConfigResponse is the response type for the Query/TokenConfig RPC method.
message QueryTokenConfigResponse {
  // config defines the parameters of the module.
  FeeTokenConfiguration config = 1 [ (gogoproto.nullable) = false ];
}