// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmwasm/txfees/v1/fee_token.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FeeTokenStatus int32

const (
	FeeTokenStatus_UPDATED  FeeTokenStatus = 0
	FeeTokenStatus_OUTDATED FeeTokenStatus = 1
	FeeTokenStatus_FROZEN   FeeTokenStatus = 2
)

var FeeTokenStatus_name = map[int32]string{
	0: "UPDATED",
	1: "OUTDATED",
	2: "FROZEN",
}

var FeeTokenStatus_value = map[string]int32{
	"UPDATED":  0,
	"OUTDATED": 1,
	"FROZEN":   2,
}

func (x FeeTokenStatus) String() string {
	return proto.EnumName(FeeTokenStatus_name, int32(x))
}

func (FeeTokenStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1105ad465f9fe9cb, []int{0}
}

type FeeTokenConfiguration struct {
	Denom  string         `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	PoolId string         `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Status FeeTokenStatus `protobuf:"varint,3,opt,name=status,proto3,enum=cosmwasm.txfees.v1.FeeTokenStatus" json:"status,omitempty"`
}

func (m *FeeTokenConfiguration) Reset()         { *m = FeeTokenConfiguration{} }
func (m *FeeTokenConfiguration) String() string { return proto.CompactTextString(m) }
func (*FeeTokenConfiguration) ProtoMessage()    {}
func (*FeeTokenConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1105ad465f9fe9cb, []int{0}
}
func (m *FeeTokenConfiguration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeTokenConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeTokenConfiguration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeTokenConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeTokenConfiguration.Merge(m, src)
}
func (m *FeeTokenConfiguration) XXX_Size() int {
	return m.Size()
}
func (m *FeeTokenConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeTokenConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FeeTokenConfiguration proto.InternalMessageInfo

func (m *FeeTokenConfiguration) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *FeeTokenConfiguration) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *FeeTokenConfiguration) GetStatus() FeeTokenStatus {
	if m != nil {
		return m.Status
	}
	return FeeTokenStatus_UPDATED
}

func init() {
	proto.RegisterEnum("cosmwasm.txfees.v1.FeeTokenStatus", FeeTokenStatus_name, FeeTokenStatus_value)
	proto.RegisterType((*FeeTokenConfiguration)(nil), "cosmwasm.txfees.v1.FeeTokenConfiguration")
}

func init() {
	proto.RegisterFile("cosmwasm/txfees/v1/fee_token.proto", fileDescriptor_1105ad465f9fe9cb)
}

var fileDescriptor_1105ad465f9fe9cb = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xce, 0x2f, 0xce,
	0x2d, 0x4f, 0x2c, 0xce, 0xd5, 0x2f, 0xa9, 0x48, 0x4b, 0x4d, 0x2d, 0xd6, 0x2f, 0x33, 0xd4, 0x4f,
	0x4b, 0x4d, 0x8d, 0x2f, 0xc9, 0xcf, 0x4e, 0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12,
	0x82, 0xa9, 0xd1, 0x83, 0xa8, 0xd1, 0x2b, 0x33, 0x94, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x4b,
	0xeb, 0x83, 0x58, 0x10, 0x95, 0x52, 0x92, 0x20, 0x95, 0xf9, 0xc5, 0xf1, 0x10, 0x09, 0x08, 0x07,
	0x2a, 0x25, 0x8f, 0xc5, 0xa2, 0x82, 0xc4, 0xa2, 0xc4, 0x5c, 0xa8, 0x02, 0xa5, 0x26, 0x46, 0x2e,
	0x51, 0xb7, 0xd4, 0xd4, 0x10, 0x90, 0xc5, 0xce, 0xf9, 0x79, 0x69, 0x99, 0xe9, 0xa5, 0x45, 0x89,
	0x25, 0x99, 0xf9, 0x79, 0x42, 0x22, 0x5c, 0xac, 0x29, 0xa9, 0x79, 0xf9, 0xb9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x38, 0x17, 0x7b, 0x41, 0x7e, 0x7e, 0x4e, 0x7c, 0x66,
	0x8a, 0x04, 0x13, 0x58, 0x9c, 0x0d, 0xc4, 0xf5, 0x4c, 0x11, 0xb2, 0xe2, 0x62, 0x2b, 0x2e, 0x49,
	0x2c, 0x29, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x33, 0x52, 0xd2, 0xc3, 0x74, 0xbf, 0x1e,
	0xcc, 0xa6, 0x60, 0xb0, 0xca, 0x20, 0xa8, 0x0e, 0x2d, 0x73, 0x2e, 0x3e, 0x54, 0x19, 0x21, 0x6e,
	0x2e, 0xf6, 0xd0, 0x00, 0x17, 0xc7, 0x10, 0x57, 0x17, 0x01, 0x06, 0x21, 0x1e, 0x2e, 0x0e, 0xff,
	0xd0, 0x10, 0x08, 0x8f, 0x51, 0x88, 0x8b, 0x8b, 0xcd, 0x2d, 0xc8, 0x3f, 0xca, 0xd5, 0x4f, 0x80,
	0xc9, 0xc9, 0xe9, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c,
	0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x34, 0xd2, 0x33,
	0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x9d, 0xf3, 0x8b, 0x73, 0xc3, 0x41, 0x61,
	0x00, 0x72, 0x4d, 0x8a, 0x7e, 0x05, 0x2c, 0x2c, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0,
	0x01, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x57, 0xbf, 0x1c, 0x94, 0x94, 0x01, 0x00, 0x00,
}

func (m *FeeTokenConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeTokenConfiguration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeTokenConfiguration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintFeeToken(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PoolId) > 0 {
		i -= len(m.PoolId)
		copy(dAtA[i:], m.PoolId)
		i = encodeVarintFeeToken(dAtA, i, uint64(len(m.PoolId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintFeeToken(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeeToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeeToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeTokenConfiguration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovFeeToken(uint64(l))
	}
	l = len(m.PoolId)
	if l > 0 {
		n += 1 + l + sovFeeToken(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovFeeToken(uint64(m.Status))
	}
	return n
}

func sovFeeToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeeToken(x uint64) (n int) {
	return sovFeeToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeTokenConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeTokenConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeTokenConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= FeeTokenStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeeToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeeToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeeToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeeToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeeToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeeToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeeToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeeToken = fmt.Errorf("proto: unexpected end of group")
)
