// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmwasm/txfees/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the txfees module.
type Params struct {
	TokenBaseDenom       string `protobuf:"bytes,1,opt,name=token_base_denom,json=tokenBaseDenom,proto3" json:"token_base_denom,omitempty"`
	PriceContractAddress string `protobuf:"bytes,2,opt,name=price_contract_address,json=priceContractAddress,proto3" json:"price_contract_address,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b44d997ec825dc4, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTokenBaseDenom() string {
	if m != nil {
		return m.TokenBaseDenom
	}
	return ""
}

func (m *Params) GetPriceContractAddress() string {
	if m != nil {
		return m.PriceContractAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmwasm.txfees.v1.Params")
}

func init() { proto.RegisterFile("cosmwasm/txfees/v1/params.proto", fileDescriptor_9b44d997ec825dc4) }

var fileDescriptor_9b44d997ec825dc4 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x63, 0x86, 0x4a, 0x64, 0x40, 0x28, 0xaa, 0x50, 0xe9, 0x60, 0x10, 0x53, 0xa6, 0x58,
	0x11, 0x5c, 0x80, 0x94, 0x03, 0x20, 0x16, 0x24, 0x16, 0xcb, 0x71, 0x1e, 0x69, 0x84, 0x9c, 0x17,
	0xf9, 0x99, 0x50, 0x6e, 0xc1, 0xb1, 0x18, 0x3b, 0x32, 0xa2, 0xe4, 0x22, 0x95, 0xed, 0x76, 0xf3,
	0xff, 0x7f, 0x9f, 0x64, 0xfb, 0x4f, 0x6f, 0x34, 0x92, 0xf9, 0x52, 0x64, 0x84, 0xdb, 0xbd, 0x03,
	0x90, 0x18, 0x4b, 0x31, 0x28, 0xab, 0x0c, 0x15, 0x83, 0x45, 0x87, 0x59, 0x76, 0x12, 0x8a, 0x28,
	0x14, 0x63, 0xb9, 0x5e, 0xb6, 0xd8, 0x62, 0xc0, 0xc2, 0x9f, 0xa2, 0xb9, 0xbe, 0xf6, 0x26, 0x92,
	0x8c, 0x20, 0x86, 0x23, 0xe2, 0x31, 0x89, 0x5a, 0x11, 0x88, 0xb1, 0xac, 0xc1, 0xa9, 0x52, 0x68,
	0xec, 0xfa, 0xc8, 0xef, 0xb6, 0xe9, 0xe2, 0x39, 0x5c, 0x9a, 0xe5, 0xe9, 0xa5, 0xc3, 0x0f, 0xe8,
	0xa5, 0x57, 0x65, 0x03, 0x3d, 0x9a, 0x15, 0xbb, 0x65, 0xf9, 0xf9, 0xcb, 0x45, 0xe8, 0x2b, 0x45,
	0xf0, 0xe4, 0xdb, 0xec, 0x21, 0xbd, 0x1a, 0x6c, 0xa7, 0x41, 0x6a, 0xec, 0x9d, 0x55, 0xda, 0x49,
	0xd5, 0x34, 0x16, 0x88, 0x56, 0x67, 0xc1, 0x5f, 0x06, 0xba, 0x39, 0xc2, 0xc7, 0xc8, 0xaa, 0xea,
	0x77, 0xe2, 0x6c, 0x3f, 0x71, 0xf6, 0x3f, 0x71, 0xf6, 0x33, 0xf3, 0x64, 0x3f, 0xf3, 0xe4, 0x6f,
	0xe6, 0xc9, 0x5b, 0xde, 0x76, 0x6e, 0xfb, 0x59, 0x17, 0x1a, 0x8d, 0xd8, 0x20, 0x99, 0x57, 0x3f,
	0x8a, 0xff, 0x78, 0x23, 0x76, 0xa7, 0x71, 0xdc, 0xf7, 0x00, 0x54, 0x2f, 0xc2, 0xa3, 0xef, 0x0f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x56, 0x72, 0xd2, 0x3c, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PriceContractAddress) > 0 {
		i -= len(m.PriceContractAddress)
		copy(dAtA[i:], m.PriceContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PriceContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TokenBaseDenom) > 0 {
		i -= len(m.TokenBaseDenom)
		copy(dAtA[i:], m.TokenBaseDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TokenBaseDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TokenBaseDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.PriceContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenBaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenBaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
